#!/usr/bin/env python3
"""Generate the daily annotation schedule: run the batch, then the run report.

Prints a wrapper script and a scheduler unit. Nothing is written or activated
unless `--install` is passed, and secrets are never placed on a command line —
the wrapper sources a protected environment file instead.

The scheduled job only creates ChangeSets. Approval and application stay with a
human curator holding separate credentials.
"""

from __future__ import annotations

import argparse
import os
import re
import shlex
import stat
import subprocess
import sys
from datetime import datetime
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
TIME_PATTERN = re.compile(r"^(?P<hour>[01]?\d|2[0-3]):(?P<minute>[0-5]\d)$")
LABEL_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{2,63}$")


def daily_time(value: str) -> tuple[int, int]:
    match = TIME_PATTERN.match(value.strip())
    if not match:
        raise argparse.ArgumentTypeError("time must be HH:MM in 24-hour form, for example 01:00")
    return int(match.group("hour")), int(match.group("minute"))


def label(value: str) -> str:
    if not LABEL_PATTERN.match(value.strip()):
        raise argparse.ArgumentTypeError("label must be 3-64 characters of letters, digits, dot, dash, underscore")
    return value.strip()


def absolute(value: str) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise argparse.ArgumentTypeError(f"path must be absolute: {value}")
    return path


def wrapper_script(args: argparse.Namespace) -> str:
    run_command = [
        "python3",
        str(SCRIPT_DIR / "run_annotation_workflow.py"),
        "--genome",
        str(args.genome),
        "--daily-count",
        str(args.daily_count),
        "--selection-policy",
        args.selection_policy,
        "--maximum-quality-score",
        str(args.maximum_quality_score),
        "--user-prompt",
        args.user_prompt,
        "--state-dir",
        str(args.state_dir),
        "--run-id",
        '"$RUN_ID"',
        "--output",
        '"$SUMMARY"',
        "--metrics-output",
        '"$METRICS"',
    ]
    if args.selection_policy == "random":
        # The wrapper's RUN_ID is per-day and stable, so a same-day rerun
        # resumes the same batch and the next day samples a fresh one.
        run_command += ["--random-seed", '"$RUN_ID"']
    if args.research_refresh_days:
        run_command += ["--research-refresh-days", str(args.research_refresh_days)]
    if args.full_text_policy != "prefer":
        run_command += ["--full-text-policy", args.full_text_policy]
    if args.literature_budget:
        run_command += ["--literature-budget", str(args.literature_budget)]
    if args.full_text_budget:
        run_command += ["--full-text-budget", str(args.full_text_budget)]
    if args.pricing_file:
        run_command += ["--pricing-file", str(args.pricing_file)]
    if args.agent_usage_file:
        run_command += ["--agent-usage-file", str(args.agent_usage_file)]

    quoted = []
    for item in run_command:
        quoted.append(item if item.startswith('"$') else shlex.quote(item))

    report_command = [
        "python3",
        shlex.quote(str(SCRIPT_DIR / "generate_run_report.py")),
        '"$SUMMARY"',
        "--title",
        '"Genome annotation daily run ${RUN_DATE}"',
        "--markdown-output",
        '"$REPORT_MD"',
        "--json-output",
        '"$REPORT_JSON"',
    ]

    env_line = (
        f'[ -f {shlex.quote(str(args.env_file))} ] && . {shlex.quote(str(args.env_file))}'
        if args.env_file
        else "# No environment file configured; export credentials in the service manager."
    )
    return f"""#!/bin/sh
# Generated by install_schedule.py. Runs one annotation batch and its report.
# Credentials come from the environment file, never from this command line.
set -eu
umask 077

{env_line}

RUN_DATE=$(date +%Y-%m-%d)
RUN_ID="{args.schedule_label}-$RUN_DATE"
REPORT_DIR={shlex.quote(str(args.report_dir))}
SUMMARY="$REPORT_DIR/$RUN_DATE-summary.json"
METRICS="$REPORT_DIR/$RUN_DATE-metrics.json"
REPORT_MD="$REPORT_DIR/$RUN_DATE-report.md"
REPORT_JSON="$REPORT_DIR/$RUN_DATE-report.json"
mkdir -p "$REPORT_DIR"

# Confirm both services answer before submitting research.
python3 {shlex.quote(str(SCRIPT_DIR / 'start_services.py'))} --check-only

# A non-zero batch exit still leaves a usable summary; the report must run.
set +e
{' '.join(quoted)}
WORKFLOW_STATUS=$?
set -e

if [ -f "$SUMMARY" ]; then
  {' '.join(report_command)}
else
  echo "No run summary at $SUMMARY; the batch failed before writing one." >&2
fi

exit "$WORKFLOW_STATUS"
"""


def launchd_plist(args: argparse.Namespace, hour: int, minute: int, wrapper_path: Path) -> str:
    log_dir = args.report_dir / "logs"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{args.schedule_label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>{wrapper_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>{hour}</integer>
    <key>Minute</key><integer>{minute}</integer>
  </dict>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>{log_dir}/{args.schedule_label}.out.log</string>
  <key>StandardErrorPath</key><string>{log_dir}/{args.schedule_label}.err.log</string>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
"""


def systemd_units(args: argparse.Namespace, hour: int, minute: int, wrapper_path: Path) -> tuple[str, str]:
    service = f"""[Unit]
Description=Genome annotation daily batch and run report

[Service]
Type=oneshot
ExecStart=/bin/sh {wrapper_path}
"""
    timezone_line = f"Timezone={args.timezone}\n" if args.timezone else ""
    timer = f"""[Unit]
Description=Run the genome annotation batch daily

[Timer]
OnCalendar=*-*-* {hour:02d}:{minute:02d}:00
{timezone_line}Persistent=true

[Install]
WantedBy=timers.target
"""
    return service, timer


def cron_line(args: argparse.Namespace, hour: int, minute: int, wrapper_path: Path) -> str:
    prefix = f"CRON_TZ={args.timezone}\n" if args.timezone else ""
    return f"{prefix}{minute} {hour} * * * /bin/sh {wrapper_path}\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a daily annotation batch schedule")
    parser.add_argument("--genome", type=absolute, required=True)
    parser.add_argument("--daily-count", type=int, default=10)
    parser.add_argument("--at", type=daily_time, default="01:00", help="Daily start time, HH:MM (default: 01:00)")
    parser.add_argument(
        "--timezone",
        help="IANA timezone for systemd/cron. launchd always uses the machine's local time; "
        "pass --scheduler systemd or cron when a specific timezone matters.",
    )
    parser.add_argument("--scheduler", choices=("launchd", "systemd", "cron"), default=None)
    parser.add_argument("--schedule-label", type=label, default="genome-annotation-daily")
    parser.add_argument(
        "--selection-policy", choices=("low-quality", "coordinate", "random"), default="low-quality"
    )
    parser.add_argument("--maximum-quality-score", type=float, default=70)
    parser.add_argument("--research-refresh-days", type=int, default=365)
    parser.add_argument("--full-text-policy", choices=("prefer", "require", "abstract-allowed"), default="prefer")
    parser.add_argument("--literature-budget", type=int)
    parser.add_argument("--full-text-budget", type=int)
    parser.add_argument(
        "--user-prompt",
        default="Refine this gene annotation feature using organism-specific evidence and precise citations",
    )
    parser.add_argument("--state-dir", type=absolute, required=True)
    parser.add_argument("--report-dir", type=absolute, required=True, help="Where daily summaries and reports are written")
    parser.add_argument("--env-file", type=absolute, help="Protected file exporting credentials for the job")
    parser.add_argument("--pricing-file", type=absolute)
    parser.add_argument("--agent-usage-file", type=absolute)
    parser.add_argument(
        "--install",
        action="store_true",
        help="Write the wrapper and scheduler unit to disk and activate the schedule",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    hour, minute = args.at if isinstance(args.at, tuple) else daily_time(args.at)
    scheduler = args.scheduler or ("launchd" if sys.platform == "darwin" else "systemd")
    if scheduler == "launchd" and args.timezone:
        print(
            f"NOTE: launchd runs at the machine's local time; --timezone {args.timezone} is not applied. "
            "Use --scheduler cron or systemd for an explicit timezone.",
            file=sys.stderr,
        )

    wrapper_dir = args.state_dir / "schedule"
    wrapper_path = wrapper_dir / f"{args.schedule_label}.sh"
    wrapper = wrapper_script(args)

    if scheduler == "launchd":
        unit_path = Path.home() / "Library" / "LaunchAgents" / f"{args.schedule_label}.plist"
        units = {unit_path: launchd_plist(args, hour, minute, wrapper_path)}
    elif scheduler == "systemd":
        base = Path.home() / ".config" / "systemd" / "user"
        service, timer = systemd_units(args, hour, minute, wrapper_path)
        units = {
            base / f"{args.schedule_label}.service": service,
            base / f"{args.schedule_label}.timer": timer,
        }
    else:
        units = {}

    if not args.install:
        print(f"# Scheduler: {scheduler}; daily at {hour:02d}:{minute:02d}")
        print(f"# Wrapper script -> {wrapper_path}\n")
        print(wrapper)
        for path, content in units.items():
            print(f"\n# ---- {path} ----\n")
            print(content)
        if scheduler == "cron":
            print("\n# ---- crontab entry ----\n")
            print(cron_line(args, hour, minute, wrapper_path))
        print("# Nothing was written. Re-run with --install to write and activate this schedule.")
        return 0

    wrapper_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "logs").mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text(wrapper, encoding="utf-8")
    wrapper_path.chmod(stat.S_IRWXU)
    written = [wrapper_path]
    for path, content in units.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)
        written.append(path)

    if scheduler == "launchd":
        unit_path = next(iter(units))
        subprocess.run(["launchctl", "unload", str(unit_path)], check=False, capture_output=True)
        result = subprocess.run(["launchctl", "load", str(unit_path)], check=False, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"ERROR: launchctl load failed: {result.stderr.strip()}", file=sys.stderr)
            return 1
    elif scheduler == "systemd":
        for command in (
            ["systemctl", "--user", "daemon-reload"],
            ["systemctl", "--user", "enable", "--now", f"{args.schedule_label}.timer"],
        ):
            result = subprocess.run(command, check=False, capture_output=True, text=True)
            if result.returncode != 0:
                print(f"ERROR: {' '.join(command)} failed: {result.stderr.strip()}", file=sys.stderr)
                return 1
    else:
        print("# Add this line to the operator's crontab (crontab -e):")
        print(cron_line(args, hour, minute, wrapper_path))

    print(f"Installed {scheduler} schedule at {hour:02d}:{minute:02d} daily.")
    for path in written:
        print(f"  wrote {path}")
    print(f"  reports -> {args.report_dir}")
    print(f"  generated at {datetime.now().astimezone().isoformat()}")
    if not args.env_file:
        print(
            "WARNING: no --env-file was given. The scheduled job inherits only the service manager's "
            "environment and will fail if CodeXomics/DGR credentials are not exported there.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    os.umask(0o077)
    raise SystemExit(main())
